---
- hosts: all
  remote_user: vagrant
  tasks:
    - name: Include kafka role
      include_role:
        name: ../../roles/kafka
  vars:
    # install kafka
    kafka_scala_version: 3.3.1
    kafka_version: 2.13
    url_download_kafka: https://dlcdn.apache.org/kafka/{{ kafka_scala_version }}/kafka_{{ kafka_version }}-{{ kafka_scala_version }}.tgz