---
- hosts: all
  become: true
  tasks:
    - name: download jdk
      get_url:
        url: https://download.oracle.com/java/18/archive/jdk-18.0.2.1_linux-x64_bin.tar.gz
        dest: /opt/jdk-18.0.2.1_linux-x64_bin.tar.gz

    - name: extract jdk
      unarchive:
        src: /opt/jdk-18.0.2.1_linux-x64_bin.tar.gz
        dest: /opt
        remote_src: yes

    - name: set jdk env
      lineinfile:
        path: /etc/profile
        state: present
        line: "{{ item }}"
      with_items:
        - 'export JAVA_HOME="/opt/jdk-18.0.2.1"'
        - "export PATH=$PATH:$JAVA_HOME/bin"

    - name: download kafka
      get_url:
        url: https://dlcdn.apache.org/kafka/3.3.1/kafka_2.13-3.3.1.tgz
        dest: /opt/kafka_2.13-3.3.1.tgz

    - name: extract kafka
      unarchive:
        src: /opt/kafka_2.13-3.3.1.tgz
        dest: /opt
        remote_src: yes

    - name: start kafka with kraft
      shell: |
        cd /opt/kafka_2.13-3.3.1
        KAFKA_CLUSTER_ID="$(bin/kafka-storage.sh random-uuid)"
        bin/kafka-storage.sh format -t $KAFKA_CLUSTER_ID -c config/kraft/server.properties
        bin/kafka-server-start.sh config/kraft/server.properties

    - name: CREATE A TOPIC TO STORE YOUR EVENTS
      shell: |
        cd /opt/kafka_2.13-3.3.1
        bin/kafka-topics.sh --create --topic quickstart-events --bootstrap-server localhost:9092

    - name: check topic is created successfully
      shell: |
        bin/kafka-topics.sh --describe --topic quickstart-events --bootstrap-server localhost:9092

    # - name: create a topic
    # - name: create an user
