---

- name: download kafka
  get_url:
    url: https://dlcdn.apache.org/kafka/3.3.1/kafka_2.13-3.3.1.tgz
    dest: /opt/kafka_2.13-3.3.1.tgz

- name: extract kafka
  unarchive:
    src: /opt/kafka_2.13-3.3.1.tgz
    dest: /opt
    remote_src: yes

- name: start kafka with kraft
  shell: |
    cd /opt/kafka_2.13-3.3.1
    KAFKA_CLUSTER_ID="$(bin/kafka-storage.sh random-uuid)"
    sudo bin/kafka-storage.sh format -t $KAFKA_CLUSTER_ID -c config/kraft/server.properties
    sudo bin/kafka-server-start.sh config/kraft/server.properties